version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    groups:
      actions-patch:
        patterns:
        - "*"
        update-types:
        - "patch"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
