name: Update libde265

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - run: wget -O version.json "https://api.github.com/repos/strukturag/libde265/releases/latest"
      - name: Get latest version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: 'version.json'
            prop_path: 'tag_name'
      - run: "sed -i 's/libde265-version: .*$/libde265-version: [\"${{steps.version.outputs.prop}}\"]/g' .github/workflows/build.yml"
      - run: "sed -i 's/\"v/\"/g' .github/workflows/build.yml"
      - run: rm version.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.0
        with:
            token: ${{ secrets.PAT }}
            commit-message: 'Bump libde265 to ${{steps.version.outputs.prop}}'
            committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
            branch: 'libde265-${{steps.version.outputs.prop}}'
            delete-branch: true
            title: 'Bump libde265 to ${{steps.version.outputs.prop}}'
            body: 'https://github.com/strukturag/libde265/releases/tag/${{steps.version.outputs.prop}}'
